version: '3.1'

services:
    db:
        image: mysql:8.0.35
        restart: always
        container_name: db
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - ecommerce-app

    frontend:
        build:
            context: ./frontend
            dockerfile: frontend.dockerfile
        container_name: frontend
        env_file:
            - .env
        ports:
            - 3000:3000
        networks:
            - ecommerce-app

    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - frontend
        restart: unless-stopped
        ports:
            - 80:80
        networks:
            - ecommerce-app

    backend:
        depends_on:
            - db
        restart: on-failure
        build:
            context: ./backend
            dockerfile: backend.dockerfile
        container_name: backend
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_HOST: ${MYSQL_HOST}
            FRONTEND_URL: ${FRONTEND_URL}
        ports:
            - 8080:8080
        networks:
            - ecommerce-app

volumes:
    mysql-data:
networks:
    ecommerce-app:
        name: ecommerce-app
